fixed typos

diff --git a/GLOBAL b/GLOBAL
--- a/GLOBAL
+++ b/GLOBAL
@@ -56,15 +56,11 @@ install_program(){
  		if [ "$ans" == "y" ];then
  			yum -y install $2
  		else
- 			if [ "$3" != "y" ]; then
-<<<<<<< HEAD
- 				echo "Cannot continue without $1. Exiting..."
-=======
- 				echo "Exiting..."
->>>>>>> fd8a140189a8af2f4aff60f6536d3969f029a381
- 				exit 1;
- 			fi
- 		fi
+			if [ "$3" != "y" ]; then
+				echo "Cannot continue without $1. Exiting..."
+				exit 1;
+			fi
+		fi
 	fi
 }
 
